apiVersion: v1
kind: Secret
metadata:
  name: myrocket-rocketchat
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: myrocket
type: Opaque
data:
  mongo-uri: "bW9uZ29kYjovL3JvY2tldGNoYXQ6dGVzdFBBU1NAbXlyb2NrZXQtbW9uZ29kYi1oZWFkbGVzczoyNzAxNy9yb2NrZXRjaGF0P3JlcGxpY2FTZXQ9cnMw"
  mongo-oplog-uri: "bW9uZ29kYjovL3Jvb3Q6dGVzdFBBU1Nyb290QG15cm9ja2V0LW1vbmdvZGItaGVhZGxlc3M6MjcwMTcvbG9jYWw/cmVwbGljYVNldD1yczAmYXV0aFNvdXJjZT1hZG1pbg=="