apiVersion: v1
kind: Service
metadata:
  name: myrocket-rocketchat
  annotations:
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: myrocket
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: myrocket