name: EFK

on: [workflow_dispatch]


jobs:
  deploy:
    runs-on: ubuntu-20.04
    # ...

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_KEY }}'

    # ... further steps are automatically authenticated
    - name: Deployment to GCP
      run: |
        gcloud container clusters get-credentials rocket --zone=us-central1-a
        kubectl create -f ./Rocket-Team/CD/manifests/elasticsearch/es-svc.yaml -f ./Rocket-Team/CD/manifests/elasticsearch/es-sts.yaml
        kubectl create -f ./Rocket-Team/CD/manifests/kibana/kibana-deployment.yaml -f ./Rocket-Team/CD/manifests/kibana/kibana-svc.yaml
        kubectl create -f ./Rocket-Team/CD/manifests/fluentd/fluentd-role.yaml -f ./Rocket-Team/CD/manifests/fluentd/fluentd-sa.yaml -f ./Rocket-Team/CD/manifests/fluentd/fluentd-rb.yaml -f ./Rocket-Team/CD/manifests/fluentd/fluentd-ds.yaml
